apiVersion: v2
name: aegis-verifier
description: A Helm chart for deploying the Aegis Distributed Legitimacy Verifier Control Plane.
type: application
version: 1.3.0
appVersion: "1.1.3"
keywords:
  - aegis
  - security
  - zero-trust
  - tpm-attestation
